const ProductTypes = {
    SAVE_TRANSACTION: "SAVE_TRANSACTION",
    DEDUCTION_TRANSACTION: "DEDUCTION_TRANSACTION",
    PLUS_TRANSACTION: "PLUS_TRANSACTION",
    DEL_TRANSACTION: "DEL_TRANSACTION",
    HISTORY_TRANSACTION: "HISTORY_TRANSACTION"
}

export default ProductTypes;